name: Deploy Trigger

on:
  push:
    branches: [ main ]

jobs:
  trigger-app:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger application
      env:
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        echo "Triggering deploy at: ${{ env.APP_URL }}/api/deploy-trigger"
        curl -X POST ${{ env.APP_URL }}/api/deploy-trigger
        echo "Deploy triggered"
