name: Deploy Trigger

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  trigger-app:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger application
      env:
        APP_URL: ${{ secrets.APP_URL }}  # Add this secret in your GitHub repository settings
      run: |
        curl -X POST ${{ env.APP_URL }}/api/deploy-trigger \
        -H "Content-Type: application/json" \
        -d '{
          "deployId": "${{ github.sha }}",
          "deployDetails": "Deployment from ${{ github.ref }} by ${{ github.actor }}"
        }'
