name: Deploy Trigger

on:
  push:
    branches: [ main ]

jobs:
  trigger-app:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger application
      env:
        APP_URL: ${{ secrets.APP_URL }}  # Ensure that APP_URL is being pulled from GitHub secrets
      run: |
        # Log the URL to verify that it's being set correctly
        echo "Using URL: ${{ env.APP_URL }}/api/deploy-trigger"
        
        # Now trigger the deploy
        echo "Triggering deploy at: ${{ env.APP_URL }}/api/deploy-trigger"
        curl -X POST ${{ env.APP_URL }}/api/deploy-trigger \
        -H "Content-Type: application/json" \
        -d '{"deployId": "12345", "deployDetails": "Deploying version 1.0"}'
        echo "Deploy triggered"
